config/routes.rb
Rails.application.routes.draw do

  resources :budgets

  resources :categories, :except => :show

  resources :users

  root 'welcome#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  get "account_settings" => "users#account_settings"
  put "account_settings" => "users#update"
  post "/up" => "budgets#update_chart"
  get "/load/:cid" => "budgets#load_chart"
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  default_scope -> { order(date_of_budget: :desc) }
  #validates :name, :user_id, :amount, presence: true
  validates :name, :amount, :date_of_budget, presence: true
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
    before_action :require_login, only: [:index, :show, :new, :edit, :create, :update, :delete, :destroy]
    before_action :set_budget, only: [:show, :edit, :update, :delete, :destroy]
    before_action :all_budgets, only: [:index, :create, :update, :delete, :destroy, :test]
    respond_to :html, :js, :json
    #override default layout by the fixed bootstrap
    layout "fixed"

    # GET /load_chart/1
    def load_chart
        @cid = params[:cid]
    end

    # POST /up
    def update_chart
        @mydate = params[:date]
        @chart_type = params[:chart_type]
    end

    # GET /budgets
    # GET /budgets.json
    def index
    end

    # GET /budgets/1
    # GET /budgets/1.json
    def show
        check_user
    end

    # GET /budgets/new
    def new
        @budget = Budget.new
        @categories = Category.all
    end

    # GET /budgets/1/edit
    def edit
        check_user
        @categories = Category.all
    end

    # POST /budgets
    # POST /budgets.json
    def create
        @budget = Budget.new(budget_params)
        @budget.user_id = current_user.id
        @budget.save
    end

    # PATCH/PUT /budgets/1
    # PATCH/PUT /budgets/1.json
    def update
        @categories = Category.all
        @budget.update(budget_params)
    end

    def delete
    end

    # DELETE /budgets/1
    # DELETE /budgets/1.json
    def destroy
        @budget.destroy
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_budget
            @budget = Budget.find(params[:id])
        end

        def all_budgets
            @budgets = current_user.budgets
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def budget_params
            params.require(:budget).permit(:name, :description, :is_expense, :category_id, :amount, :date_of_budget)
        end

        #users can only see their own budget
        def check_user
            if current_user != @budget.user
                redirect_to(root_url)
            end
        end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<%- model_class = Budget -%>

<tr>
    <td><%= budget.date_of_budget.strftime("%d.%m.%Y") %></td>
    <td class="
    <%=
    if budget.is_expense
        "text-danger text-right"
    else
        "text-success text-right"
    end %>
    "><%= number_with_precision( budget.amount, precision: 2, separator: '.', delimiter: '\'') %></td>
    <td><%= link_to budget.name, budget_path(budget) %></td>
    <td><%= budget.description %></td>
    <td><%=
    if budget.category_id.nil?
        "-"
    else
        budget.category.name
    end
    %></td>
    <td>
        <%= link_to glyph(:edit, {:tag => :span}),
        edit_budget_path(budget),
        :class => 'btn btn-xs btn-primary', remote: true %>
        <%= link_to glyph(:trash, {:tag => :span}),
        budget,
        :remote => true,
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' %>
    </td>
</tr>

app/views/budgets/_chart.html.erb
<%- model_class = Budget -%>
<%
if @mydate.blank?
    @mydate_m = Time.now.strftime("%m")
    @mydate_y = Time.now.strftime("%Y")
else
    @mydate_m = Date.parse(@mydate).strftime("%m")
    @mydate_y = Date.parse(@mydate).strftime("%Y")
%>
<% end %>


<%= form_tag("/up", { :class => "form-horizontal chart-date", :id => "form-my", remote: true }) do %>
<div class="form-group">
    <%= label_tag(:date, nil, {:class => 'col-sm-2 control-label'}) %>
    <div class="col-sm-3">
        <%= text_field_tag(:date, nil, {:class => 'form-control date-picker-my'}) %>
        <%= hidden_field_tag 'chart_type', custom_chart %>
    </div>
    <div class="col-sm-2">
        <%= submit_tag("Update", {:class => 'btn btn-primary'}) %>
    </div>
</div>
<% end %>
<script type="text/javascript">
//This will display only the month and the year
$(function() {
    $('.date-picker-my').datepicker( {
        changeMonth: true,
        changeYear: true,
        showButtonPanel: false,
        dateFormat: 'MM yy',
        onClose: function(dateText, inst) {
            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
            $(this).datepicker('setDate', new Date(year, month, 1));
        }
    });
    $('.date-picker-my').click(function(){
        $('.ui-datepicker-calendar').css("display", "none");
    });
});
</script>

<!-- by month -->
<% if custom_chart == 1 %>
    <%= column_chart current_user.budgets.where('extract(year from date_of_budget) = ?', @mydate_y).group("CASE WHEN is_expense = true THEN 'Expense' ELSE 'Saving' END").group_by_month(:date_of_budget, format: "%b %Y").sum(:amount), library: { colors: ['green', '#dc3912'] } %>

<!-- by day -->
<% elsif custom_chart == 2 %>
    <%= column_chart current_user.budgets.where('extract(year from date_of_budget) = ? AND extract(month from date_of_budget) = ?', @mydate_y, @mydate_m).group("CASE WHEN is_expense = true THEN 'Expense' ELSE 'Saving' END").group_by_day(:date_of_budget, format: "%-d").sum(:amount),
    library: {
        colors: ['#dc3912', 'green'],
        title: 'Expenses and savings for the selected month',
        hAxis: { title: 'Day' }
        } %>

<!-- by year -->
<% elsif custom_chart == 3 %>
    <%= column_chart current_user.budgets.group("CASE WHEN is_expense = true THEN 'Expense' ELSE 'Saving' END").group_by_year(:date_of_budget, format: "%Y", last: 5).sum(:amount),
    library: {
        colors: ['green', '#dc3912'],
        title: 'Expenses and savings for the past 5 years',
        hAxis: { title: 'Year' }
        } %>

<!-- month details -->
<% else %>
    <%= pie_chart current_user.budgets.where('extract(year from date_of_budget) = ? AND extract(month from date_of_budget) = ?', @mydate_y, @mydate_m).group("CASE WHEN is_expense = true THEN 'Expense' ELSE 'Saving' END").sum(:amount),
    library: {
        pieSliceText: 'value',
        colors: ['green', '#dc3912'],
        title: 'Expenses and savings for the selected month'
        } %>
    <%= pie_chart current_user.budgets.joins(:category).where('extract(year from date_of_budget) = ? AND extract(month from date_of_budget) = ?', @mydate_y, @mydate_m).group("categories.name").sum(:amount),
    library: {
        pieSliceText: 'value',
        title: 'Expenses and savings for the selected month by category'
        } %>
<% end %>

app/views/budgets/_form.html.erb
<%= form_for @budget, remote: true, :html => { :class => "form-horizontal budget" } do |f| %>

<script>
$(function() {
    $("#budget_date_of_budget").datepicker({dateFormat: "yy-mm-dd"});
});
</script>

<% if @budget.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @budget.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

<div class="form-group">
    <%= f.label :name, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@budget[:name]) %>
</div>
<div class="form-group">
    <%= f.label :description, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%= error_span(@budget[:description]) %>
</div>
<div class="form-group">
    <%= f.label :is_expense, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.check_box :is_expense, :class => 'form-control' %>
    </div>
    <%= error_span(@budget[:is_expense]) %>
</div>
<div class="form-group">
    <%= f.label :category_id, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.collection_select(:category_id, @categories, :id, :name, :include_blank => "Please select") %>
    </div>
    <%= error_span(@budget[:category_id]) %>
</div>

<div class="form-group">
    <%= f.label :amount, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@budget[:amount]) %>
</div>

<div class="form-group">
    <%= f.label "Date", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.date_field :date_of_budget, :class => 'form-control' %>
    </div>
    <%= error_span(@budget[:date_of_budget]) %>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    budgets_path, :class => 'btn btn-default', :id => 'cancel' %>
    </div>
</div>

<% end %>

app/views/budgets/create.js.erb
$('#budgets').html("<%= j (render @budgets) %>");
$('#budget-form').slideUp(350);

app/views/budgets/destroy.js.erb
$('#budgets').html("<%= j (render @budgets) %>");

app/views/budgets/edit.html.erb
<%- model_class = Budget -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/budgets/edit.js.erb
$('#budget-form').html("<%= j (render 'form') %>");
$('#budget-form').slideDown(350);
$('#cancel').click(function(){
    $('#budget-form').slideUp(350);
});

app/views/budgets/index.html.erb
<%- model_class = Budget -%>

<div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_budget_path, remote: true, :class => 'btn btn-primary' %>
</div>

<div id="budget-form" style="display:none;"></div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th><%= model_class.human_attribute_name(:amount) %></th>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:description) %></th>
            <th><%= model_class.human_attribute_name(:category_id) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
    </thead>
    <tbody id="budgets">
        <%= render @budgets %>
    </tbody>
</table>

<% if @budgets.count == 0 %>
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="alert fade in alert-info">No data available. Add your expenses and savings now.</div>
    </div>
</div>

<% else %>

<div class="row"><p></p></div>
<div class="row">
    <div class="col-lg-12">
        <div class="btn-group" role="group" aria-label="Chart Type">
            <%= link_to "Month details", "/load/4", remote: true, :class => 'chart_type btn btn-default', data: { cid: "4" } %>
            <%= link_to "By year", "/load/3", remote: true, :class => 'chart_type btn btn-default', data: { cid: "3" } %>
            <%= link_to "By month", "/load/1", remote: true, :class => 'chart_type btn btn-default', data: { cid: "1" } %>
            <%= link_to "By day", "/load/2", remote: true, :class => 'chart_type btn btn-default', data: { cid: "2" } %>
        </div>
    </div>
</div>
<p>
    <div id="chart"><%= render 'chart', custom_chart: 4 %></div>
</p>

<% end %>

app/views/budgets/load_chart.js.erb
console.log("cid <%= @cid %>");
var cid = "<%= @cid %>";

if (cid == 1) {
    $('#chart').html("<%= j (render 'chart', custom_chart: 1) %>");
    console.log("load_chart 1");
} else if (cid == 2) {
    $('#chart').html("<%= j (render 'chart', custom_chart: 2) %>");
    console.log("load_chart 2");
} else if (cid == 3) {
    $('#chart').html("<%= j (render 'chart', custom_chart: 3) %>");
    console.log("load_chart 3");
} else {
    $('#chart').html("<%= j (render 'chart', custom_chart: 4) %>");
    console.log("load_chart 4");
}

app/views/budgets/new.html.erb
<%- model_class = Budget -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/budgets/new.js.erb
$('#budget-form').html("<%= j (render 'form') %>");
$('#budget-form').slideDown(350);
$('#cancel').click(function(){
    $('#budget-form').slideUp(350);
});

app/views/budgets/show.html.erb
<%- model_class = Budget -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @budget.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @budget.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_expense) %>:</strong></dt>
  <dd><%= @budget.is_expense %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= number_with_precision( @budget.amount, precision: 2, separator: '.', delimiter: '\'') %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%=
        if @budget.category_id.nil?
            "-"
        else
            @budget.category.name
        end
    %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @budget.user.username %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              budgets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_budget_path(@budget), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              budget_path(@budget),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/budgets/update.js.erb
$('#budgets').html("<%= j (render @budgets) %>");
$('#budget-form').slideUp(350);

app/views/budgets/update_chart.js.erb
console.log("cid <%= @chart_type %>");
var cid = "<%= @chart_type %>";

if (cid == 1) {
    $('#chart').html("<%= j (render 'chart', custom_chart: 1) %>");
    console.log("load_chart 1");
} else if (cid == 2) {
    $('#chart').html("<%= j (render 'chart', custom_chart: 2) %>");
    console.log("load_chart 2");
} else if (cid == 3) {
    $('#chart').html("<%= j (render 'chart', custom_chart: 3) %>");
    console.log("load_chart 3");
} else {
    $('#chart').html("<%= j (render 'chart', custom_chart: 4) %>");
    console.log("load_chart 4");
}