config/routes.rb
Rails.application.routes.draw do

  resources :budgets

  resources :categories, :except => :show

  resources :users

  root 'welcome#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  get "account_settings" => "users#account_settings"
  put "account_settings" => "users#update"
  post "/up" => "budgets#update_chart"
  get "/load/:cid" => "budgets#load_chart"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    has_many :budgets, dependent: :destroy
    validates :username, presence: true, length: { maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

    attr_accessor :password
    before_save :encrypt_password
    validates_confirmation_of :password

    def encrypt_password
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end


    def self.authenticate(email, password)
        user = User.where(email: email).first
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user
        else
            nil
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:index, :show, :edit, :update, :destroy]
    before_action :check_authorization, only: [:index]
    before_action :set_user, only: [:show, :edit, :update, :delete, :destroy]
    before_action :all_users, only: [:index, :create, :update, :delete, :destroy]
    respond_to :html, :js
    #override default layout by the fixed bootstrap
    layout "fixed"

    # GET /users
    # GET /users.json
    def index
    end

    # GET /users/1
    # GET /users/1.json
    def show
        check_user
    end

    # GET /users/new
    def new
        @user = User.new
    end

    # GET /users/1/edit
    def edit
        if !admin?
            check_user
        end
    end

    # POST /users
    # POST /users.json
    def create
        @user = User.new(user_params)

        if @user.save
            if current_user.nil?
                flash[:notice] = 'Your account was successfully created. You can now login.'
                redirect_to log_in_path
            end
        end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
        @user.update(user_params)
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
        @user.destroy
    end

    def delete
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_user
            @user = User.find(params[:id])
        end

        def all_users
            @users = User.all
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def user_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation, :is_admin, :is_active)
        end

        def account_settings
            @user = current_user
        end

        def check_user
            if current_user != @user
                redirect_to(root_url)
            end
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% #when creating an account, the form should not use remote:true %>
<%= form_for @user, remote: !current_user.nil?, :html => { :class => "form-horizontal user" } do |f| %>

<% if @user.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

<div class="form-group">
    <%= f.label :username, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.text_field :username, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:username]) %>
</div>
<div class="form-group">
    <%= f.label :email, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
</div>
<div class="form-group">
    <%= f.label :password, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:password]) %>
</div>
<div class="form-group">
    <%= f.label :password_confirmation, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:password_confirmation]) %>
</div>
<% if logged_in? and admin? %>
<div class="form-group">
    <%= f.label :is_active, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.check_box :is_active, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:is_active]) %>
</div>
<div class="form-group">
    <%= f.label :is_admin, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
        <%= f.check_box :is_admin, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:is_admin]) %>
</div>
<% end %>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
        <%= f.submit "Create", :class => 'btn btn-primary' %>
        <% if logged_in? and admin? %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default', :id => 'cancel' %>
        <% elsif logged_in? and admin? == false %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path(@user), :class => 'btn btn-default', :id => 'cancel' %>
        <% else %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            root_path, :class => 'btn btn-default', :id => 'cancel' %>
        <% end %>
    </div>
</div>
<% end %>

app/views/users/_user.html.erb
<%- model_class = User -%>

<tr>
    <td><%= link_to user.username, user_path(user) %></td>
    <td><%= user.is_active %></td>
    <td><%= user.created_at.strftime("%d.%m.%Y %H:%M") %></td>
    <td><%= user.updated_at.strftime("%d.%m.%Y %H:%M") %></td>
    <td>
        <%= link_to glyph(:edit, {:tag => :span}),
        edit_user_path(user), :class => 'btn btn-xs btn-primary', remote: true %>
        <%= link_to glyph(:trash, {:tag => :span}),
        user_path(user),
        :remote => true,
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' %>
    </td>
</tr>

app/views/users/create.js.erb
$('#users').html("<%= j (render @users) %>");
$('#user-form').slideUp(350);

app/views/users/destroy.js.erb
$('#users').html("<%= j (render @users) %>");

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
    <h1>Edit profile of <%= @user.username %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/edit.js.erb
$('#user-form').html("<%= j (render 'form') %>");
$('#user-form').slideDown(350);
$('#cancel').click(function(){
    $('#user-form').slideUp(350);
});

app/views/users/index.html.erb
<%- model_class = User -%>

<div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_user_path, remote: true, :class => 'btn btn-primary' %>
</div>

<div id="user-form" style="display:none;"></div>
<table class="table table-striped">
    <thead>
        <tr>
            <th><%= model_class.human_attribute_name(:username) %></th>
            <th><%= model_class.human_attribute_name(:is_active) %></th>
            <th><%= model_class.human_attribute_name(:created_at) %></th>
            <th><%= model_class.human_attribute_name(:updated_at) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
    </thead>
    <tbody id="users">
        <%= render @users %>
    </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
new_user_path,
:class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
    <% if logged_in? %>
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
    <% else %>
    <h1>Create your account now</h1>
    <% end %>
</div>
<%= render :partial => 'form' %>

app/views/users/new.js.erb
$('#user-form').html("<%= j (render 'form') %>");
$('#user-form').slideDown(350);
$('#cancel').click(function(){
    $('#user-form').slideUp(350);
});

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
    <h1>Profile of <%= @user.username %></h1>
</div>

<dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
    <dd><%= @user.username %></dd>
    <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
    <dd><%= @user.email %></dd>

<% if admin? %>
    <dt><strong><%= model_class.human_attribute_name(:is_active) %>:</strong></dt>
    <dd><%= @user.is_active %></dd>
    <dt><strong><%= model_class.human_attribute_name(:is_admin) %>:</strong></dt>
    <dd><%= @user.is_admin %></dd>
<% end %>
    <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
    <dd><%= @user.created_at %></dd>
    <dt><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
    <dd><%= @user.updated_at %></dd>
</dl>


<% if admin? %>
<%= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'  %>
<% else %>
<%= link_to t('.back', :default => t("helpers.links.back")), budgets_path, :class => 'btn btn-default'  %>
<% end %>

<%= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user),
:method => 'delete',
:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
:class => 'btn btn-danger' %>

app/views/users/update.js.erb
$('#users').html("<%= j (render @users) %>");
$('#user-form').slideUp(350);