config/routes.rb
Rails.application.routes.draw do

  resources :budgets

  resources :categories, :except => :show

  resources :users

  root 'welcome#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  get "account_settings" => "users#account_settings"
  put "account_settings" => "users#update"
  post "/up" => "budgets#update_chart"
  get "/load/:cid" => "budgets#load_chart"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Budget Manager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "//code.jquery.com/ui/1.11.2/jquery-ui.js" %>
</head>
<body>

    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Budget Manager</a>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Home", "/"  %></li>
                    <li><%= link_to "My expenses", "/budgets"  %></li>
                    <% if logged_in? and admin? %>
                    <li><%= link_to "Categories", "/categories"  %></li>
                    <li><%= link_to "Users", "/users"  %></li>
                    <% end %>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <% if current_user %>
                    <li><%= link_to glyph(:user, {:tag => :span}) + " " + current_user.username, "/users/" + current_user.id.to_s %></li>
                    <li><%= link_to glyph(:log_out, {:tag => :span}), log_out_path %></li>
                    <% else %>
                    <li><%= link_to "Sign up", "/users/new" %></li>
                    <li><%= link_to glyph(:log_in, {:tag => :span}), log_in_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%= bootstrap_flash %>



                <%= yield %>
            </div>
        </div><!--/row-->

        <footer>
            <p class="text-center">&copy; Web Engineering Mini-project - 2014</p>
        </footer>

    </div> <!-- /container -->

</body>
</html>